variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

stages:
  - build

build-container:
  image: docker
  services: 
    - docker:dind
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - echo "$RAILS_MASTER_KEY" > config/master.key
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $DOCKER_IMAGE -f Dockerfile .
    - docker push $DOCKER_IMAGE